In [179]:
import tensorflow as tf
import warnings
warnings.filterwarnings("ignore")
print(tf.__version__)

2.18.0


In [180]:
from tensorflow.keras.preprocessing.text import one_hot


In [181]:
sentences = ['lion is the king of the jungle',
             'I like chicken tikka',
             'atul is a tech enthusiast', 
             'i am a good developer',
             'birds fly in the sky',
             'glass of juice', 
             'glass of milk']

In [182]:
voc_size = 500 #vocabulary size

In [183]:
onehot_rep = [one_hot(words, voc_size) for words in sentences]
onehot_rep

[[220, 342, 174, 416, 162, 174, 441],
 [126, 136, 398, 458],
 [287, 342, 143, 466, 127],
 [126, 412, 143, 442, 368],
 [297, 224, 117, 174, 492],
 [138, 162, 466],
 [138, 162, 327]]

In [184]:
import numpy as np
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [185]:
sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding='pre', maxlen=sent_length)
embedded_docs

array([[  0, 220, 342, 174, 416, 162, 174, 441],
       [  0,   0,   0,   0, 126, 136, 398, 458],
       [  0,   0,   0, 287, 342, 143, 466, 127],
       [  0,   0,   0, 126, 412, 143, 442, 368],
       [  0,   0,   0, 297, 224, 117, 174, 492],
       [  0,   0,   0,   0,   0, 138, 162, 466],
       [  0,   0,   0,   0,   0, 138, 162, 327]])

In [186]:
embedding_dim= 10

In [187]:
model = Sequential()
model.add(Embedding(input_dim = voc_size, output_dim=embedding_dim,input_length=sent_length ))
model.build(input_shape=(None, sent_length))
model.compile(optimizer='adam', loss= 'mse')

In [188]:
model.summary()

Model: "sequential_20"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_17 (Embedding)        │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [189]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step
[[[-7.6726787e-03  3.1167101e-02  9.0258718e-03  3.2706860e-02
    2.8620552e-02  4.1087236e-02  3.2471824e-02 -1.6558290e-02
    4.8871446e-02 -1.2707435e-02]
  [ 5.3436682e-04 -7.5719245e-03 -2.9659979e-03 -3.0587912e-03
   -4.7420837e-02 -6.2227137e-03  4.8694078e-02  4.5814838e-02
   -3.4805823e-02 -2.3503626e-02]
  [-1.8094458e-02  4.4259597e-02  3.8090322e-02 -4.0876865e-03
    2.6230875e-02  2.1186460e-02  3.3419952e-03  2.6585348e-03
   -1.4411785e-02 -4.4769254e-02]
  [-4.1136276e-02  3.1776454e-02  4.2490575e-02 -3.7898004e-02
   -1.8233370e-02 -2.3255348e-02  4.2928789e-02  4.3331910e-02
    3.1936560e-02 -4.9710002e-02]
  [ 3.4247402e-02 -1.2874056e-02 -1.0222435e-02  3.3927966e-02
    2.0385813e-02 -7.5903647e-03 -1.4099702e-03 -4.3849360e-02
    4.1948725e-02  4.8372913e-02]
  [ 3.5221305e-02 -4.8480131e-02 -9.8199248e-03 -3.2188497e-02
    3.6797825e-02 -9.0763792e-03 -3.7947010e-02  2.8661266e-03
   -3.9018203e-02  3.9132360e-02]
 

In [190]:
embedded_docs[0]

array([  0, 220, 342, 174, 416, 162, 174, 441])

In [195]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step


array([[[-0.00767268,  0.0311671 ,  0.00902587,  0.03270686,
          0.02862055,  0.04108724,  0.03247182, -0.01655829,
          0.04887145, -0.01270743],
        [ 0.00053437, -0.00757192, -0.002966  , -0.00305879,
         -0.04742084, -0.00622271,  0.04869408,  0.04581484,
         -0.03480582, -0.02350363],
        [-0.01809446,  0.0442596 ,  0.03809032, -0.00408769,
          0.02623088,  0.02118646,  0.003342  ,  0.00265853,
         -0.01441178, -0.04476925],
        [-0.04113628,  0.03177645,  0.04249058, -0.037898  ,
         -0.01823337, -0.02325535,  0.04292879,  0.04333191,
          0.03193656, -0.04971   ],
        [ 0.0342474 , -0.01287406, -0.01022243,  0.03392797,
          0.02038581, -0.00759036, -0.00140997, -0.04384936,
          0.04194872,  0.04837291],
        [ 0.0352213 , -0.04848013, -0.00981992, -0.0321885 ,
          0.03679783, -0.00907638, -0.03794701,  0.00286613,
         -0.0390182 ,  0.03913236],
        [-0.04113628,  0.03177645,  0.04249058, -0.0